internxt/drive-server-wip

- test/app.e2e-spec.ts
- Fixes e2e tests related to the items limit number that is currently failing
> [_]: fix/items-size-limit-tests

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/trash/trash.controller.ts
Added an endpoint that deletes all files on the user trash.
> [WT-22] Feature: create endpoint to clear trash

- src/externals/notifications/listeners/send-link.listener.ts
- src/modules/send/dto/create-send-link.dto.ts
- src/modules/send/send.controller.ts
- src/modules/send/send.usecase.ts
Adds the code to the link when sharing it via mail. Related to [Send Web #8](https://github.com/internxt/send-web/pull/8/files)
> [_]: fix/add-code-to-mail

- src/app.module.ts
- src/externals/bridge/bridge.module.ts
- src/externals/bridge/bridge.service.spec.ts
- src/externals/bridge/bridge.service.ts
- src/externals/crypto/crypto.spec.ts
- src/externals/crypto/crypto.ts
Added a service to call to be able to call bridge endpoints
> [WT-33] Feat: add bridge service

- .github/workflows/run-tests.yml
- README.md
- migrations/20211105180600-create_users_referrals_table.js
- migrations/20220309180600-create-deleted-files-table.js
- migrations/20220309190600-create-deleted-files-trigger.js
- migrations/20220309190601-create-clear_orphan_folders_by_user-procedure.js
- migrations/20220624130000-update-shares-table-with-columns.js
- migrations/20220718082248-add-version-to-send-link-item.js
- package.json
- src/app.module.ts
- src/config/sequelize.js
- src/modules/send/send.usecase.spec.ts
- src/modules/send/send.usecase.ts
- test/app.e2e-spec.ts
- yarn.lock
Tested with postgres locally, everything seemed ok
Before deploying this to prod we need to make one last sync between the tables ~3 mins
> [WT-30]: Feat/migration to postgres wip

- src/modules/trash/dto/controllers/delete-item.dto.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.usecase.spec.ts
- src/modules/trash/trash.usecase.ts
Adds delete multiple trashed items
> [WT-29]feat: add delete trashed items

- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.usecase.ts
> [WT-34] feat: delete single item

- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/run-tests.yml
Run the test when committing or opening a pr on the branch develop and master
> [WT-62] chore: run test when committing or opening a pr on develop

- migrations/20220919083117-add-password-to-shared-links.js
- src/modules/send/send-link-item.domain.ts
- src/modules/send/send-link.domain.ts
- src/modules/send/send-link.repository.ts
- src/modules/send/send.usecase.spec.ts
- src/modules/send/send.usecase.ts
- src/modules/share/share.domain.ts
- src/modules/share/share.repository.ts
- src/modules/share/share.usecase.spec.ts
- src/modules/share/share.usecase.ts
Adds a nullable password field to shares and send links table
> [WT-76] feat: add password field to shared links

- src/modules/send/send.usecase.spec.ts
- src/modules/share/share.module.ts
- src/modules/share/share.usecase.spec.ts
> [_] fix: update share and send test

- src/modules/file/dto/file.dto.ts
- src/modules/file/file.domain.ts
- src/modules/folder/dto/folder.dto.ts
- src/modules/folder/folder.domain.ts
- src/modules/share/dto/share.dto.ts
- src/modules/share/share.controller.ts
- src/modules/share/share.domain.ts
Added DTO classes to file, folder and share to type the response of get share due.
Deleted the field user from file json/DTO. Currently is not populated but if the are changes to the repository could be added to the response:
> [_] chore: type share response

- src/config/configuration.ts
- src/externals/newsletter/index.ts
- src/externals/notifications/events/sign-up.event.ts
- src/externals/notifications/listeners/analytics.listener.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.usecase.ts
- Migrates the analytics part of the signup from drive-server.
- Migrates the subscribe to newsletter on signup from drive-server.
NEW ENVIRONMENT VARIABLES:
- `MAILERLITE_API_KEY`
- `MAILERLITE_GROUP_ID`
> [_]: feat/add-newsletter-and-analytics-sign-up

- src/modules/share/share.controller.ts
- src/modules/user/referrals.repository.ts
- Migrates the application of the share-file referral from drive-server
> [_]: fix/apply-share-file-referral

- src/modules/file/file.usecase.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/trash/trash.usecase.ts
- Added user validation to deleteFolder
- Fixed tests with this change
> [_]: Feature/add user validation to deleteFolder

- migrations/20221003090000-create-thumbnails-table.js
- Added migration for Thumbnails
> [WT-100]: Create migration for Thumbnails

- migrations/20220916100000-update-share-file-delete.js
- Recovered sharedLinks FK migration temporarily deleted
> [_]: Fix/Recovered migration temporarily deleted

- package.json
- src/lib/analytics.ts
- yarn.lock
- Adds rudder analytics
Note: secrets are already configured
> [_]: Feat/ruddder analytics

- src/main.ts
- src/modules/send/dto/create-send-link.dto.ts
- src/modules/send/send.controller.ts
- src/modules/send/send.usecase.ts
- src/modules/share/dto/create-share.dto.ts
- src/modules/share/dto/update-share.dto.ts
- src/modules/share/share.controller.ts
- src/modules/share/share.usecase.spec.ts
- src/modules/share/share.usecase.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.usecase.ts
- test/app.e2e-spec.ts
- test/share.mother.ts
- Fixes some issues that appeared integrating with drive-web
- Changes encryption to deterministic with salt
> [WT-65]: Refactor/shared links

- .github/workflows/input-test
Add a new action to try run it from actions page
> [_] chore: add workflow with inputs to be able to run on actions page

- src/modules/share/share.usecase.ts
> [_]: fix(share-usecase): send encryptedCode

- migrations/20221010100000-add-column-sendLinks-parentFolder.js
- src/modules/send/dto/create-send-link.dto.ts
- src/modules/send/send-link-item.domain.ts
- src/modules/send/send-link.domain.ts
- src/modules/send/send-link.repository.ts
- src/modules/send/send.usecase.ts
- Implement upload folders logic on send functions
- Added migration for 'parent_folder' property
> [WT-35]: Feature/send upload folders

- src/externals/newsletter/index.ts
- Fixes adding to group and creating user on mailerlite
> [_]: Refactor(newsletter-service): fixes group adding to mailerlite

- src/externals/notifications/listeners/send-link.listener.ts
- Removed subitems from send email
> [_] Fix/Remove subitems from send email

- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
- Exposes an endpoint to refresh user auth tokens
> [_]: feat/refresh-tokens

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.repository.ts
- src/modules/share/share.repository.ts
- src/modules/share/share.usecase.ts
- Added trash filter to shared items
> [_]: Fix/Add trash filter to shared items

- src/modules/file/file.domain.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/share/share.controller.ts
- src/modules/share/share.usecase.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.usecase.ts
- Fixed deleting permanently trash items bug
> [_]: Fix/delete permanently trash items

- src/modules/share/share.controller.ts
- src/modules/share/share.repository.ts
- src/modules/share/share.usecase.ts
- Fixes delete link in front 
drive-web wasn't receiving the id of the link and so it was deleting `undefined`
> [_]: Fix/delete link in web

- src/modules/share/share.usecase.ts
The folder sharing was not handled for cases when the file is created by a guest on shared workspaces.
The solution is checking which is the owner of the folder when sharing that folder on a shared workspace (sometimes is the host, sometimes is some guest, both can share folders of each other if they want).
These changes allow a guest in a shared workspace to be able to create, update and delete shares related to folders.
> [_]: fix/folder-sharing-shared-workspace

- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
- Added trycatch to ignore errors on signup
> [_]: Fix/Add trycatch to ignore errors on signup

- src/modules/folder/folder.usecase.ts
- src/modules/share/dto/get-down-files.dto.ts
- src/modules/share/share.controller.ts
- src/modules/share/share.usecase.ts
- Added parentId mandatory param 
Bonus:
- Fixed filenames not being decrypted when downloading shared files/folders
> [WT-251]: Fix/Unauthorized access files

- migrations/20221109110000-add-unique-columns-files.js
- migrations/20230103122430-add-plain-name-to-folder.js
- migrations/20230103122435-add-plain-name-to-file.js
- migrations/20230103122440-create-index-files-plain-name.js
- migrations/20230103122445-create-index-folder-plain-name.js
- Added migrations to keep pace with drive-server
> [WT-145]: feat/add-plain-name-to-files-and-folders 

- src/modules/folder/folder.repository.ts
- Fixed trash bug where orphan folders (folders with deleted parentId) where not being deleted permanently
> [WT-302]: Fix orphan folders trash bug

- src/modules/file/file.controller.ts
- src/modules/file/file.module.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.module.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
Exposes files & folders controllers, which include:
- Get files & folders orphan, existent, and trashed files
- Remove orphan files & folders
> [_]: feat/files-folders-controllers

- migrations/20230215131844-add-postgresql-uuid-extension.js
- migrations/20230215132330-add-uuid-column-to-folders.js
Introduced changes:
- Enables `uuid-ossp` extension on Postgres.
- Adds a `uuid` to each folder.
> [_]: feat/add-uuid-to-folders

- src/modules/file/dto/file.dto.ts
- src/modules/file/file.domain.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/dto/folder.dto.ts
- src/modules/folder/folder.attributes.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.model.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/user/user.attributes.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
- Added query to search files by substring
- Added pagination to max 5 elements
> [WT-318]: Feat/Query to search files by substring

- src/modules/file/dto/file.dto.ts
- src/modules/file/file.domain.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/dto/folder.dto.ts
- src/modules/folder/folder.attributes.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.model.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/user/user.attributes.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
Reverts internxt/drive-server-wip#141
> Revert "[WT-318]: Feat/Query to search files by substring"

- src/externals/bridge/bridge.service.ts
- src/externals/notifications/events/referral-redeemed.event.ts
- src/modules/file/dto/file.dto.ts
- src/modules/file/file.domain.ts
- src/modules/file/file.module.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/dto/folder.dto.ts
- src/modules/folder/folder.attributes.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.model.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/send/send.controller.ts
- src/modules/share/share.module.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.usecase.ts
- src/modules/user/user.attributes.ts
- src/modules/user/user.usecase.ts
These changes allow trash to be paginated as we should stop loading all the resources at the same time.
> [WT-334]: feat/paginate-trash

- src/modules/trash/trash.controller.ts
Logs errors with a detailed context when moving content to trash fails.
> [_]: fix/log-move-items-to-trash-errors

- src/externals/crypto/crypto.spec.ts
- src/externals/logger/index.ts
- src/externals/notifications/listeners/auth.listener.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
These changes fix relative imports that were going out and in of src, thus, breaking the output build on execution time.
> [_]: fix/correct-import-paths-from in-out src

- src/modules/user/user.controller.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.usecase.ts
Removes the transactional behavior of the users' creation
> [PB-412]: feat/remove-transaction-from-users

- src/modules/trash/trash.controller.ts
Add a log when a request to retrieve files and folders for the trash fails
> [_]: Add log to trash get paginated items

- src/externals/notifications/events/items-to-trash.event.ts
- src/externals/notifications/events/notification.event.ts
- src/externals/notifications/listeners/notification.listener.ts
- src/modules/trash/trash.controller.ts
- Added uuid to move to trash socket event
> [PB-718] feature/Add email and uuid to socket emit events

- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/private-share-folder/dto/get-items-and-shared-folders.dto.ts
- src/modules/private-share-folder/private-sharing-folder.domain.ts
- src/modules/private-share-folder/private-sharing-folder.model.ts
- src/modules/private-share-folder/private-sharing.controller.ts
- src/modules/private-share-folder/private-sharing.repository.ts
- src/modules/private-share-folder/private-sharing.usecase.spec.ts
- src/modules/private-share-folder/private-sharing.usecase.ts
- Get items and Shared folders in the same format to use in the same component
> [_]: fix/same format getting items and shared folders

- migrations/20230818075304-private-sharing-indexes.js
Changes: 
- Adds indexes for the most queried fields on private-sharing
> [_]: feat/private-sharing-indexes

- src/modules/file/file.usecase.ts
- src/modules/folder/folder.usecase.ts
- src/modules/trash/trash.usecase.ts
Issue:
- Did not completely delete the files
update:
- Set to count folders to delete
> [PB-685]: fix/trash-not-being-emptied-properly

- src/modules/sharing/dto/get-items-and-shared-folders.dto.ts
- src/modules/sharing/models/index.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.ts
Return `files` on the shared items list.
> [_] feat/ added files to sharing/folders endpoint

- src/modules/sharing/sharing.repository.ts
changes
- Removed sharingId from select attributes and group by items_id.
> [PB-974]: fix/prevent duplication if owner requests shared items

- src/modules/folder/folder.controller.ts
Endpoint:
`GET /folders/:folderId/file?name=anyFilename&type=jpg`
> [_] feat: check file by plainname and type endpoint

- src/modules/sharing/sharing.repository.ts
Just close this if not needed anymore.
> chore: changed bulkcreate to update in replace created user function

- src/modules/user/user.controller.ts
A new endpoint has been added to check if the user exists or not and, if the user exists, to check if the user has a subscription.
> [_]: feat/check if the user exists or has sub

- .gitignore
- package.json
- src/app.module.ts
- src/externals/notifications/events/event.ts
- src/modules/feature-limit/feature-limit.usecase.ts
- src/modules/feature-limit/limit.domain.ts
- src/modules/feature-limit/limits.enum.ts
- src/modules/feature-limit/models/tier.model.ts
- src/modules/file/file.controller.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.attributes.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/fuzzy-search/look-up.domain.ts
- src/modules/sharing/dto/create-sharing-role.dto.ts
- src/modules/sharing/sharing.controller.spec.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.module.ts
- src/modules/trash/trash.usecase.ts
- src/modules/user/user.model.ts
- test/fixtures.ts
- yarn.lock
Reverts internxt/drive-server-wip#279
> Revert "Chore: mergin storage days limit with the current test branch"

- src/lib/jitsi.ts
- Fixes meet JWT nbf date generation
> [_]: Fix/Meet JWT nbf date

- src/modules/folder/folder.controller.ts
Reverts enforce id type when listing metadata
> [_]: Fix/Reverts enforce id type when listing metadata

- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
We need to provide the frontend team an endpoint to decline user invitations.
> feat: remove workspace invite

- migrations/20240513092428-add-room-to-meet-beta-users.js
- src/lib/jitsi.ts
- src/lib/jwt.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.usecase.ts
- Reduced meet token expiration time to 1 minute
- Added a new public endpoint that can generate an anonymous meet token
- Added optional room parameter for a better beta token management
- Added unit tests
> [PB-2022]: Feat/Invited meet users can join calls

- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/user/user.usecase.ts
- Adds missing parent folder UUID to initial folders (Family & Personal)
> [_]: Fix/Add parent uuid to intial folders

- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
This PR exposes an endpoint so the frontend team is able to get the credentials for uploading to the workspace network.
> [_] Feat/add get workspace credentials

- src/modules/workspaces/dto/edit-workspace-details-dto.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
https://inxt.atlassian.net/browse/PB-2081
Endpoint to allow workspace owners to edit basic workspace details (name and description).
> [PB-2081]: feat/edit basic workspace details

- migrations/20240612153998-add-deleted-files-table.js
- migrations/20240612154000-add-deleted-folders-table.js
We had some missing migrations. This just adds them
> [_] chore: added-deleted-files-and-folders-missing-migrations

- migrations/20240614091229-add-creationTime-to-files-table.js
- Fixes the creation_time SQL migration script
> [_]: fix/sql-creation_time-migration-script

- seeders/20240227151200-public-sharings-user.js
This is a seeder to fix public sharings in test environments.
> [_] chore: added public user to seeders for environments

- src/modules/gateway/dto/delete-workspace.dto.ts
- src/modules/gateway/dto/update-workspace-storage.dto.ts
- src/modules/gateway/gateway.controller.spec.ts
- src/modules/gateway/gateway.controller.ts
- src/modules/gateway/gateway.module.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Enable options through the gateway to allow deletion of the workspace and updating of the storage of a workspace. Using the flow of B2B subscriptions of the user (owner) of the space as a trigger.
> [PB-2119, PB-2115] Feat: managing the Workspace Gateway

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/trash/dto/controllers/delete-item.dto.ts
- src/modules/trash/dto/controllers/delete-items.dto.spec.ts
- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.controller.ts
- src/modules/workspaces/guards/workspaces-resources-in-behalf.decorator.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
Files are now removable with uuid and enabled for workspaces.
> Feat/enable delete files with UUID

- src/modules/trash/trash.controller.ts
Fixed a bug with the loop through items  when there are only uuids. Also parallelized the process of removing the folders from trash.
> fix: remove items from trash

- src/externals/mailer/mailer.service.ts
- src/modules/workspaces/dto/create-workspace-invite.dto.ts
- src/modules/workspaces/workspaces.usecase.ts
The initial sendGrid template did not take into account the message show on Figma. This PR adds the context and field needed for it.
> feat: send messages when invitation is sent

- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
I sent a PR some days ago. This PR adds tests for it and fixes a miss calculation.
> [_] fix: added tests and fixed get workspace usage

- src/modules/gateway/gateway.controller.spec.ts
- src/modules/gateway/gateway.controller.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- Search user by email (Gateway)
- https://github.com/internxt/payments/pull/71
> Feat/gateway: allow to search user by email in the gateway routes

- migrations/20240709150203-create-workspace-table.js
- migrations/20240709150243-create-workspace-teams-table.js
- migrations/20240709150318-create-workspace-default-team-fk.js
- migrations/20240709150335-create-workspace-users-table.js
- migrations/20240709150349-create-workspace-items-user-table.js
- migrations/20240709150415-create-workspace-team-user-table.js
- migrations/20240709150441-create-workspace-invites-table.js
- migrations/20240709150517-add-avatar-field-into-workspaces-table.js
- migrations/20240709150539-add-root-folder-id-to-workspace-table.js
- migrations/20240709150557-add-root-folder-id-to-workspace-user-table.js
- migrations/20240709150751-remove-sharing-shared-with-constraint.js
- migrations/20240709150816-add-shared-with-type-to-sharings.js
- migrations/20240709150840-add-last-size-sync-column.js
This PR intends to add the related tables to production before releasing workspaces.
> [_] chore: workspaces-database-migrations

- src/modules/folder/folder.domain.spec.ts
- src/modules/folder/folder.domain.ts
- src/modules/sharing/sharing.domain.ts
- src/modules/workspaces/attributes/workspace-invite.attribute.ts
- src/modules/workspaces/attributes/workspace-items-users.attributes.ts
- src/modules/workspaces/attributes/workspace-team-users.attributes.ts
- src/modules/workspaces/attributes/workspace-team.attributes.ts
- src/modules/workspaces/attributes/workspace-users.attributes.ts
- src/modules/workspaces/attributes/workspace.attributes.ts
- src/modules/workspaces/domains/workspace-invite.domain.ts
- src/modules/workspaces/domains/workspace-item-user.domain.ts
- src/modules/workspaces/domains/workspace-team-user.domain.ts
- src/modules/workspaces/domains/workspace-team.domain.ts
- src/modules/workspaces/domains/workspace-user.domain.spec.ts
- src/modules/workspaces/domains/workspace-user.domain.ts
- src/modules/workspaces/domains/workspaces.domain.ts
- src/modules/workspaces/models/workspace-invite.model.ts
- src/modules/workspaces/models/workspace-items-users.model.ts
- src/modules/workspaces/models/workspace-team-users.model.ts
- src/modules/workspaces/models/workspace-team.model.ts
- src/modules/workspaces/models/workspace-users.model.ts
- src/modules/workspaces/models/workspace.model.ts
- src/modules/workspaces/repositories/team.repository.spec.ts
- src/modules/workspaces/repositories/team.repository.ts
- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- test/fixtures.spec.ts
- test/fixtures.ts
Files extracted from https://github.com/internxt/drive-server-wip/pull/287
Additions:
1. Workspaces models
2. Workspaces domains
3. Workspaces repositories
4. Small modifications to sharings and folders domain that does not break the current behavior
5. Tests for respective new files.
> [_] chore: workspaces new domains, repositories and models

- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/workspaces/workspaces.controller.ts
The current usage route was overlapping with the general workspace usage route
> [_] fix: change type in repository and modify route name

- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
We provided an endpoint to deactivate users, however, there is no endpoint to reactivate users.
> [_] feat: added activate workspace user

- src/modules/workspaces/guards/workspaces.guard.spec.ts
- src/modules/workspaces/guards/workspaces.guard.ts
- src/modules/workspaces/workspaces.usecase.ts
Deactivated users should not have access to the workspace.
> [_] fix: guard now checks if user is deactivated

- src/modules/gateway/dto/update-workspace-storage.dto.ts
- src/modules/gateway/gateway.controller.spec.ts
- src/modules/gateway/gateway.controller.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Update numberOfSeats and both workspace and members space limits when gateway is triggered via a subscriptionChanged event from payments.
> [PB-2387]: fix/upgrade or downgrade b2b plans

- src/modules/trash/trash.controller.ts
Enable sorting for `GET trash/paginated ` endpoint.
> [PB-2946]: feat/update trash controller to support sorting

- src/modules/file/dto/create-file.dto.ts
- src/modules/file/file.usecase.ts
This is to mirror this behavior https://github.com/internxt/drive-server/pull/441
> [_] fix: align new file endpoint with old drive-server implementation

- src/modules/user/user.usecase.ts
This aligns the udpatePassword endpoint with the previous implementation: https://github.com/internxt/drive-server/pull/382
> [_] fix: update last password changed at on password change

- src/modules/user/user.controller.ts
This endpoint is missing the tokens like the old API. This fixes that
> [_] fix: return tokens on password change

- src/modules/file/file.usecase.ts
- src/modules/folder/folder.usecase.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Allow sorting in `GET /:workspaceId/trash`
> [PB-3057]: feat/allow sorting workspaces trash

- migrations/20241007154046-add-find-folder-by-path-function.js
- src/lib/path.spec.ts
- src/lib/path.ts
- src/modules/file/file.controller.spec.ts
- src/modules/file/file.controller.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- Adds get folder by path
- Adds get file by path
> [PB-2217]: feat/get-item-by-path

- src/modules/workspaces/domains/workspaces.domain.ts
- src/modules/workspaces/dto/create-workspace-invite.dto.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
This PR reintroduces variabe storage limit assignment to workspace members throught the use of invites.
> [PB-2524]: chore/reintroduce variable limits in invitations

- migrations/20241029132704-update--workspace-owners-space-limit.js
- src/modules/workspaces/workspaces.usecase.ts
Recalculate correctly the space assigned to the owner
> [_]: fix/calculate space assigned to owner

- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Assign unused space to owner when modifying member's storage or when upgrading/downgrading workspace plan
> [PB-3215]: feat/modify members storage

- src/modules/fuzzy-search/fuzzy-search.module.ts
- src/modules/fuzzy-search/fuzzy-search.usecase.spec.ts
- src/modules/fuzzy-search/fuzzy-search.usecase.ts
- src/modules/fuzzy-search/look-up.model.ts
- src/modules/fuzzy-search/look-up.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.module.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
New endpoint to allow fuzzy search within workspaces. This searches through workspace items created by the requesting user.
> [PB-3046]: feat/implement fuzzy search functionality within workspaces

- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Throw bad request exception when attempting to asign a user a space limit higher than workspaceLimit / numberOfSeats.
> [_]: fix/add validation when updating user space

- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
When a user leaves or when they are removed from the workspace they where not being deleted from teams, this PR fixes that.
> [_]: fix/delete user from teams whenever they are removed from/exit workspace

- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.spec.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- Fixed folder metadata not being found when it is on the trash
> [_]: fix/getFolderByUuid-not-found-when-trashed

- migrations/20250131123014-increase-sharing-encryption-key-size.js
- migrations/20250131124626-increase-sharing-invitation-encryption-key-size.js
Encrypted keys are longer when encrypted with hybrid encryption. We need to increase the size of this field.
> [_] chore: increase sharings encryption key size

- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
This is just a PR to get user root folder without any extra function in between like decrypting name.
> [_] chore: get root folder on access

- src/modules/file/file.controller.ts
- src/modules/folder/folder.controller.ts
Adding the exception filter to log strange exception that is being thrown with some items.
> [PB-3686] chore: added extended exception filter to move files and folders 

- src/modules/auth/auth.controller.ts
- src/modules/user/user.usecase.ts
Enhance endpoint `Auth/LoginAccess` with detailed logging for better error tracking
> [_]: Feat/add login-access logs

- package.json
- src/modules/file/file.controller.ts
- src/modules/file/guards/upload.guard.spec.ts
- src/modules/file/guards/upload.guard.ts
- yarn.lock
- It adds a guard to enforce client version restrictions during file uploads
> [_]: feat/block-uploads-on-affected-versions

- src/externals/notifications/storage.notifications.service.spec.ts
- src/externals/notifications/storage.notifications.service.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Add notification events for users leaving or joining a workspace
> [PB-4112]: feat/add workspace joined and left notification events

- src/externals/asymmetric-encryption/asymmetric-encryption.service.ts
- src/modules/user/user.controller.ts
1. Fixes `[AUTH/PREREGISTER] ERROR: value too long for type character varying(476)`
2. Adds extended exception filter for better tracking
> [_] fix: pre created users assign revocation certificate

- package.json
- src/modules/sharing/sharing.domain.ts
- src/modules/user/pre-created-user.domain.ts
- src/modules/user/pre-created-users.attributes.ts
- src/modules/user/pre-created-users.model.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- test/fixtures.ts
Reverts internxt/drive-server-wip#493
There's an issue when sharings are created with pre created users. I am reverting this to investigate the issue
> Revert "[_] Feat: add kyber support for pre created users"

- Dockerfile
- development.Dockerfile
- infrastructure/development.Dockerfile
- infrastructure/preview.Dockerfile
1. Node image changed from node-alpine to just node defacto image.
> [_] chore: changed docker node image

- src/modules/sharing/dto/response/get-item-sharing-info.dto.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
Changes
1. Created endpoint to get general sharing info from item
2. Marked `/:itemType/:itemId/type` endpoint as deprecated
> [_] feat(sharings): add item sharing info endpoint

- src/modules/sharing/sharing.service.ts
This PR just changes the way we make the requests to bridge so we do not wait for each request to be finished. The response time of this endpoint should be improved by this.
> [_] chore(public-sharings): handle requests to bridge concurrently

- src/modules/thumbnail/dto/create-thumbnail.dto.ts
- src/modules/thumbnail/thumbnail.usecase.ts
1. Added uuid support to thumbnails.
2. Added extra logic to the dto validator, either id or uuid should be provided, and not both.
> feat(thumbnails): added uuid support to thumbnails

- src/modules/file/file.controller.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
> [_] chore: add status to folder responses

- src/modules/cache-manager/cache-manager.service.ts
- src/modules/gateway/gateway.usecase.ts
Adding some temporary debug logs surrounding limit cache
> [_]: debug/add debug logs

- src/modules/user/dto/responses/generate-mnemonic.dto.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
This endpoint is used by the mobile app.
> [_] feat: added /bits endpoint

- src/externals/crypto/crypto.service.ts
- src/lib/jwt.ts
- src/modules/user/dto/legacy-recover-account.dto.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
Reverts internxt/drive-server-wip#567
> [_] Add backs -> "feat(recover-account): recover account with legacy backup"

- package.json
- src/common/http-global-exception-filter.exception.spec.ts
- src/externals/multer/index.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/trash/trash.controller.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/workspaces/guards/workspaces-resources-in-behalf.decorator.ts
- src/modules/workspaces/guards/workspaces-resources-in-behalf.types.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.spec.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.ts
- yarn.lock
Fixing code smells introduced in 2024
> [PB-4418]: chore/fix codesmells introduced in 2024

- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.usecase.spec.ts
Increase test coverage in trash module
> [PB-4417]: chore/enhance unit tests for TrashController and TrashUseCases

- src/modules/workspaces/guards/workspaces-resources-in-behalf.decorator.spec.ts
- src/modules/workspaces/repositories/team.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.spec.ts
Increase test coverage in the workspaces modules
> [PB-4417]: chore/improve workspace module test coverage

- jest.setup.js
- package.json
- src/modules/file/file.controller.spec.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
Improve file controller and usecase test coverage, added jest config to avoid bigInt serialization issues.
> [PB-4417]: chore/file controller and usecase test coverage

- package.json
- yarn.lock
Closes https://github.com/internxt/drive-server-wip/security/dependabot/90
> [_] chore(deps): upgrade platform-express patch version

- src/externals/notifications/storage.notifications.service.spec.ts
- src/externals/notifications/storage.notifications.service.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/workspaces/workspaces.controller.ts
Add strict type instead of any to EventArguments. Also, send FileDto and FolderDto in FILE_CREATED, FILE_UPDATED, FOLDER_CREATED and FOLDER_UPDATED.
> Send DTOs in websocket notifications

- Dockerfile
- development.Dockerfile
- infrastructure/development.Dockerfile
- infrastructure/preview.Dockerfile
- jest.setup.js
Upgrade node images to version 22.17.0
> [PB-4409]: chore/update Node.js version to 22.17.0

- migrations/20250707135035-add-not-null-constraint-on-thumbnail.js
Add not null constraint to file_uuid field on thumbnails table
> [_]: feat(migrations)/add not-null constraint on file_uuid in thumbnails table

- src/modules/sharing/sharing.repository.spec.ts
- test/fixtures.spec.ts
- test/fixtures.ts
Improve test coverage in sharings repository
> [PB-4417]: chore/improve sharings repository test coverage

- src/modules/sharing/sharing.controller.spec.ts
Improve test coverage in sharings controller
> [PB-4417]: chore/sharing controller test coverage

- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
- test/fixtures.ts
Improve test coverage in sharings service
> [PB-4417]: chore/sharings service test coverage

- src/modules/user/attempt-change-email.repository.spec.ts
- src/modules/user/user.repository.spec.ts
- src/modules/user/user.usecase.spec.ts
Improve test coverage in user module
> [PB-4417]: chore/user module test coverage

- src/externals/captcha/captcha.service.ts
- src/modules/auth/auth.controller.ts
This PR removes conditional captcha protection from the login endpoint. We need to work on desktop applications before enabling this check.
> [_]: fix/remove conditional Catcha guard

- src/modules/user/dto/responses/refresh-avatar.dto.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
This PR implements a new endpoint where we return a new avatar URL for use on the client side.
> [_]: feature/refresh avatar user

- src/modules/user/user.controller.ts
- Adds newToken to the register users response
> [_]: feat/add-missing-newToken-property

- src/modules/file/dto/replace-file.dto.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
ModificationTime should be received if a file is replaced.
> [_] fix: add modification date to replace file endpoint

- src/modules/sharing/dto/response/get-folders-in-shared-folder.dto.ts
- src/modules/sharing/dto/response/shared-base.dto.ts
- src/modules/sharing/dto/response/shared-file-item.dto.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/sharing/sharing.service.ts
Unit tests will be added in another PR
> [_] fix: added owner info to get files in shared folder endpoint

- src/modules/sharing/dto/create-sharing.dto.ts
- Fixed invalid white space formatting for itemType
> [_]: fix/correct-invalid-whitespace

- migrations/20250828150710-create-notifications-table.js
- migrations/20250828150711-create-user-notification-status-table.js
Added database migration files for notifications:
- notifications table for storing notification data
- user_notification_status table for tracking user notification statuses
More [info](https://inxt.atlassian.net/wiki/spaces/T/pages/682557442/Notifications)
Related:
- https://github.com/internxt/drive-server-wip/pull/684
> [_] feat(notifications): add notifications database tables migrations

- src/modules/user/user.controller.ts
- Fixes the get user response endpoint not returning the same properties as the other endpoints like create user or login/access
> [_]: fix/user-response-properties

- src/modules/file/dto/move-file.dto.ts
- src/modules/file/file.controller.spec.ts
- src/modules/file/file.controller.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- Adds rename operation (optional) when moving files
> [PB-4899]: feat/add-rename-operation-to-move-files-endpoint

- migrations/20250919134806-seed-lifetime-tiers.js
This PR adds new tiers for the lifetime subscriptions.
> [PB-4942] feat/seed-lifetime-tiers

- src/modules/auth/constants.ts
- src/modules/gateway/dto/get-user-credentials.dto.ts
- src/modules/gateway/gateway.controller.ts
- src/modules/gateway/gateway.module.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- Allow get users credentials via gateway
> [_] feat: expose user public info gateway
