internxt/drive-server-wip

- migrations/20221003080000-create-index-folders-bucket.js
Changes introduced:
- Creates an index with the field `bucket` from the `folders` table. 
This fixes the slow response from the database when the folders table starts to be big enough to make a select by this field to find the folders. Backups rely on this field a lot, so the response starts to be slow in those cases where backups are involved.
> [_]: fix/create-index-folders-using-bucket-field

- src/modules/share/share.repository.ts
- src/modules/share/share.usecase.ts
Listing shares was not handled for shared workspaces. 
Listing shares whose owner is the host or any guest solves this issue.
These changes also remove the usage of a total count which is completely unnecessary and an overload for the database.
> [_]: fix/list-shares-shared-workspace

- src/middlewares/passport.ts
- src/modules/user/user.usecase.ts
Fix new token payload not being wrapped inside the `email` element.
Example of the `newToken` payload data:
```json
{
"payload": {
"uuid": "e46732fa-5443-46f9-897b-1cf0b32bf259",
"email": "pr@internxt.com",
"name": "My",
"lastname": "Internxt",
"username": "pr@internxt.com",
"sharedWorkspace": true,
"networkCredentials": {
"user": "jvalles@internxt.com",
"pass": "$2a$08$74gAUBkBLswuQYuYsM/A3OnhoHu.Jds32tu3N/LkxD0w277Ka8ncG"
}
},
"iat": 1669733468,
"exp": 1670943741
}
```
> [MT-83] fix: sign token with payload correctly

- src/config/configuration.ts
- src/externals/bridge/bridge.service.ts
- src/modules/user/user.usecase.ts
These changes allow a failed signup to signup again. 
**_Issue_**
We create one account on Drive and one in our network for each signup. When the network account was created successfully but the Drive one did not, the user was not able to signup again as the network was rejecting the email as it already existed. 
**_Solution_**
Calling to a gateway endpoint on the network that creates or updates the user if already exists. Therefore, if the signup fails, as long as the Drive account does not exist, the user will be able to signup again.
> [_]: fix/allow-failed-signups-to-register

- migrations/20230216192042-create-index-folder-uuid-files.js
As we are moving to UUIDs, the relation between files and folders is through these UUIDs, so we need to index them for the high usage they are going to get.
> [_]: feat/add-folder-uuid-files-index

- migrations/20230508130907-add-removed-column-to-folders.js
- src/modules/file/dto/file.dto.ts
- src/modules/file/file.domain.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/dto/folder.dto.ts
- src/modules/folder/folder.attributes.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.model.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.usecase.ts
Files and folders are marked as removed=true instead of removing the rows. Then, we can get an accurate idea of what actions have been performed and when. Thus, more efficient, simple mirroring could be implemented. 
Also, this allows us to manage all of the removal-related things on the background completely.
> [_]: feat/mark-resources-as-removed

- src/modules/sharing/sharing.repository.ts
1. Credentials now are not empty when listing items shared by me or with me.
> [PB-1013]: feat/owner-credentials-in-shared-listing

- src/modules/sharing/sharing.service.ts
Creating a new invite was deleting previous invites. Therefore, 1 item was not able to have more than 1 pending invite.
Steps to reproduce:
1. Invite user test@test.com to a shared folder. Dont accept the invite.
2. Invite user test2@test.com. Don't accept the invite.
Expected:
- User 1 and 2 are able to see their invitations.
Actual result:
- Invitation for user 1 is removed.
> fix: invites are not longer being deleted when a new invite is created

- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.ts
We had this implemented previously but had to rollback to align with the frontend. Now the frontend does not need this field so we are removing it again to prevent this:
> fix: prevent shared items duplication for owners

- src/lib/openpgp.ts
- src/modules/user/user.usecase.ts
Keys generated backend side are causing a crash on the frontend because of a difference between clocks. This does not happend everytime, it depends on the PC, connection and timezone. 
So to add a little tolerance, we need to rest some seconds to the creationDate of the generated keys. 
Error sent by sentry.
Error reported on github 
https://github.com/openpgpjs/openpgpjs/issues/1099
Edit:
Changed to 1 hour to have a big marging. We don´t have control of users clock.
> fix: time tolerance to openpgp keys creation

- src/modules/sharing/sharing.controller.ts
Browsers complain when you try to send a password that does not matches with ISO-8859-1 through headers.
> [PB-1483]: fix/decode sharing password header

- src/modules/user/user.repository.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
Introduced changes: 
- Get the user by `uuid` instead of by email when the email is updated to prevent an eventual consistency error
- Update the `bridge_user` respecting how the shared workspace works: 
- When the user is a host: update the `username`, the `email`, and the `brigde_user` of itself and all the guests
- When the user is a guest: update the `username` and the `email` only 
- When there is no shared workspace, update the three fields (just for that user)
> fix: handle workspace users on email change

- src/common/base-http.exception.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/folder/exception/calculate-folder-size-timeout.exception.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.spec.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/send/send.usecase.spec.ts
- src/modules/share/share.usecase.spec.ts
- src/modules/trash/trash.usecase.spec.ts
I'm using a recursive raw query to get each file of each folder belonging to folder father. 
the properties that I used to filter in the query all have indexes;  `file.folder_uuid`, `folder.uuid`, `folder.parent_uuid,` so improving the performance for each request.
> [PB-845]: feat/calculate-folder-size

- src/common/uuid.dto.spec.ts
- src/common/uuid.dto.ts
- src/modules/sharing/exception/sharing-not-found.exception.ts
- src/modules/sharing/exception/sharing.exception.ts
- src/modules/sharing/sharing.controller.spec.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
This PR is to obtain the size of a public folder.
Currently filters `sharing` for the database by `ID`, `type`, and `itemType`; If it almost does not find a result, it throws a `SHARING_NOT_FOUND` error, if it exists, it continues with the request and returns the `size` of the folder.
> [PB-845]: feat/Calculate-sharing-folder-size

- src/modules/file/file.repository.ts
Files status are being updated despite have been already DELETED. This leads to users not being able to empty their trash and might have access to files that are not in our network anymore. 
What happens:
1. File is marked as STATUS = DELETED
2. This triggers a function that saves data in a table called 'deleted_files' which is used as a queue to delete files from the network.
3. File, for some reason, is marked to STATUS != DELETED 
The send to trash function is currently targeting all files you pass to it, so it does not care what the status is.
> [PB-1617]: fix/files can not be trashed if status = deleted

- seeders/20230620032601-roles.js
- seeders/20240227151157-add-paid-plans-dev.js
We need to fill the planIds and Roles on development automatically for the CI/CD so the devops team does not need to fill them every time manually.
> chore: add role seeders

- .gitignore
- src/externals/notifications/events/event.ts
- src/modules/file/file.controller.ts
- src/modules/folder/folder.attributes.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.domain.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/fuzzy-search/look-up.domain.ts
- src/modules/share/share.usecase.spec.ts
- src/modules/sharing/dto/create-sharing-role.dto.ts
- src/modules/sharing/sharing.controller.spec.ts
- src/modules/sharing/sharing.controller.ts
- test/fixtures.ts
- Added missing parentUuid property to folders
- Added getFolderContentFolders function to get the subfolders from a folder
- Added getFolderContentFiles function to get the subfiles from a folder
- Added unit tests
> [PB-1706]: Retrieve subitems by folder UUID

- .github/workflows/build-and-publish-preview.yml
- .github/workflows/deploy-pr-preview.yml
- .github/workflows/dispatch-cleanup-pr-preview.yml
- .github/workflows/slash-command-dispatcher.yaml
- infrastructure/preview.Dockerfile
These actions would
* build and publish a Docker image with every push to the branch
* add preview label when the PR is ready_for_review (this triggers the app creation)
* clean up the created app whe the PR is closed
* build and publish a Docker image when the PR is merged
* enable slash commands to check and update the created environment
> [!NOTE]
> This PR needs this secrets to be configured in order to work
> - `PAT` - A GitHub Personal Access Token with following scopes `repo:status` `public_repo`.
> - `DOCKERHUB_USERNAME` - The username for the DockerHub account.
> - `DOCKERHUB_TOKEN` - The token for the DockerHub account.
>
> [IN-31] ci: add needed actions

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/trash/dto/controllers/move-items-to-trash.dto.spec.ts
- src/modules/trash/dto/controllers/move-items-to-trash.dto.ts
- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.controller.ts
This PR allows to add files by uuid to trash.
Either id or uuid should be provided inside the items. If none is provided, then the input is invalid.
> [PB-1740]: feat/add items to trash by uuid

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.module.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/sharing/sharing.domain.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
- src/modules/user/user.usecase.ts
This PR intends to stop sharing files/folders when you trash them. 
**Why**?
With features limits being implemented, we should stop sharing items when they are trashed to provide a smooth and clear experience. If I trash an item, I expect it to stop counting as a sharing.
**What could be improved?**
This PR adds this proccess in a sync way, however, we could also add an event listener in a future to decouple this process and make it async.
> [PB-1920]: fix/stop sharing items when they are trashed

- src/modules/workspaces/dto/change-user-role.dto.ts
- src/modules/workspaces/repositories/team.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
This PR enables changing roles of users inside a workspace (teams). 
There are only two possible roles to be assigned in the workspace (excluding owner, which is non assignable):
- Manager of a team: it is able to manage the team users, remove them for the team, etc.
- Member: has access to the team but it is not able to manage users or settings of it.
If a manager is removed from his role, them the owner of the workspace becomes the manager of that team. Teams should always have manager.
> [PB-1841] feat: added change users role in workspace team

- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
We need to show users their available workspaces so they can switch between them. We also need to show the current user's pending (to be setup) workspaces. 
This PR intends to add those two endpoints.
- Get available workspaces endpoint: retrieves the already setup workspaces the user belongs to, this endpoint is useful for owners and members of the workspace. 
- Get workspaces pending to be set up: retrieves the current user (thus, the owner of them) workspaces that are yet to be setup.
> [PB-2049]: feat/added get available and pending to be setup workspaces endpoints

- src/modules/user/user.module.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/dto/accept-workspace-invite.dto.ts
- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.module.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
This PR adds pre-created user replacement using the same logic we implemented previously for sharings and adds an endpoint to accept workspace invitations.
- When a user registers via normal flow with the invited email.
- When a user registers via a special flow (view) set for external invited users.
We use the same process as sharings (which is working OK), when the user registers and a new pair of keys are created, we use the default password we set previously to decrypt the private key of the pre-created user and use the new pair of keys to encrypt again the respective encryptionKeys.
We had problems with that previously! Sometimes the invitation is not accepted after we update the keys and the userUuid of the invitation! Please reach out to me for a further explanation.
Due to the …
> [PB-1837]: feat/accept invitation to workspace

- src/modules/gateway/dto/initialize-workspace.dto.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/workspaces/dto/setup-workspace.dto.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
We need to modify the flow of the workspaces creation. Name and address are now going to be generated with the billing address from Stripe. 
This PR makes optional those fields in the setupWorkspace function. Now we only need the owner's encrypted mnemonic to set up their user on the first access to the workspaces and mark the workspace as ready.
> feat: modified workspace creation flow

- migrations/20240515091404-create-custom-collation.js
- src/modules/file/file.repository.ts
- src/modules/folder/folder.controller.ts
Changes: 
- Add a new custom collation `custom_numeric` (icu, locale = en-u-kn-true)
- Use the new collation to sort files by name in the well-known 'natural order'
With these changes, a files list ordered like this in ascendant order by name:
- Article 1
- Article 10
- Article 2
Is going to be ordered like this: 
- Article 1
- Article 2
- Article 10
> [_]: fix/sort-files-by-name-using-natural-order

- src/modules/workspaces/repositories/team.repository.spec.ts
- src/modules/workspaces/repositories/team.repository.ts
- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
- test/fixtures.ts
This PR allows workspace users to get other members details and workspace owners to deactivate other users in the workspace.
It also fixes the endpoint to get the members of a team.
> [PB-1843, PB-1840] feat: added deactivate user and member details endpoint

- src/modules/workspaces/attributes/workspace-invite.attribute.ts
- src/modules/workspaces/attributes/workspace-users.attributes.ts
- src/modules/workspaces/domains/workspace-invite.domain.ts
- src/modules/workspaces/domains/workspace-user.domain.ts
- src/modules/workspaces/dto/workspace-user-member.dto.ts
- src/modules/workspaces/models/workspace-invite.model.ts
- src/modules/workspaces/models/workspace-users.model.ts
- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
- test/fixtures.spec.ts
- test/fixtures.ts
BigInts are not well-supported by JSON.stringify(), which is used by NestJS and Jest in many situations. This causes more problems than benefits, and using BigInts is unnecessary in our case.
Initially, using BigInts seemed like a good idea due to their support for numbers greater than the MAX_SAFE_INTEGER. However, the MAX_SAFE_INTEGER is sufficiently large for our use case.
MAX_SAFE_INTEGER = 9,007,199,254,740,991
If we consider this number as bytes, it is approximately 8,192 TB, which is more than adequate for our needs.
> [_] chore: bigint variables are now handled with number

- src/modules/user/pre-created-users.repository.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/dto/workspace-invitations-pagination.dto.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
- test/fixtures.spec.ts
- test/fixtures.ts
This PR exposes 2 new endpoints.
1. Get workspaces/invitations: retrieves current user invitations to any workspace.
2. Get workspaces/:workspaceId/invitations: retrieves pending invitations to the current workspace. Only the owner has access to this endpoint.
> [_] feat: workspaces enable endpoints to retrieve invitations

- src/common/http-exception-filter-extended.exception.spec.ts
- src/common/http-exception-filter-extended.exception.ts
- src/modules/workspaces/workspaces.controller.ts
This PR introduces ExtendedHttpExceptionFilter, which extends NestJS's BaseExceptionFilter to improve error logging for unexpected errors. Http errors are not being logged as they are expected properly.
When an unexpected error appears, we usually are not able to find logs easily due to Nestjs way of logging things (just the error message and the trace). Also, sometimes the errors are log in multiple lines and we are not able to see what's happening clearly. 
More info about this: https://docs.nestjs.com/exception-filters#inheritance
> [_] feat: added extended base http exception

- src/modules/file/dto/update-file-meta.dto.ts
- src/modules/file/file.controller.ts
- src/modules/folder/dto/create-folder.dto.ts
- src/modules/folder/dto/update-folder-meta.dto.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.usecase.ts
This is just to add two endpoints that had already created usecases but were not exposed yet.
> [_] chore: enabled folder and files creation with uuid

- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
This is to dismiss this warning and to use the operators the library provides us with
Query with substring operator
Query with sequelize literal and interpolating variables
> [_] chore: use substring operator instead of literals

- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.domain.spec.ts
- src/modules/folder/folder.domain.ts
The frontend uses this [endpoint](https://github.com/internxt/drive-server/blob/1a5400fe7da249ea96ff4423e228d9f6d25a90f1/src/app/routes/storage.ts#L838) to check if a file or folder with the same name already exists in the location (and maybe other usecases). They need the same endpoints to switch from ID to UUID usage.
> [PB-2248] feat: get folder contents with uuid

- src/modules/file/file.usecase.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.ts
Drive-web is migrating to use uuids, they need to get the rootFolder uuid when the user is created.
Also, fixed a bug that was making the endpoint fail when type is missing.
> [_]: fix/ createFile fix and rootFolderId as uuid when client is drive-web

- src/modules/workspaces/dto/change-user-assigned-space.dto.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.ts
This PR is to unblock the frontend team. I am going to add another PR with the respective tests and required refactors afterwards (tomorrow).
Added endpoint to get the total used storage in the workspace and another endpoint to change the users assigned space.
> feat: added workspace usage and change member assigned space endpoints

- src/modules/folder/folder.repository.spec.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/sharing/sharing.service.ts
The size was not being calculated correctly when folders only contained subfolders without any files.
The previous query used an INNER JOIN combined with a WHERE condition for the files, which excluded folders (and their subfolders and files) if they did not contain any files.
This PR changes the INNER JOIN to a RIGHT JOIN and moves the FILE.STATUS != 'DELETED' condition to the join clause.
Additionally, there was a small bug in this query (primarily used for public sharings). When a folder is shared, users should not download TRASHED files, so including them in the total size calculation is incorrect.
**A small improvement outside of the ticket scope:**
Due to the nature of this query, which fails when 1000 rows have been calculated, I suggest adding a field in the response to indicate …
> [BR-191]: fix: folder size now is being calculated correctly

- migrations/20240610121257-add-last-size-sync-column.js
- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/workspaces/attributes/workspace-users.attributes.ts
- src/modules/workspaces/domains/workspace-user.domain.ts
- src/modules/workspaces/models/workspace-users.model.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
- test/fixtures.ts
Due to the current files and folders structure, and the files being removed using a background process when the parent folder is deleted. We need a way to calculate the workspace member's usage on the fly. 
However, using a sum of all the files with TRASHED or EXISTS status would affect the scalability of the request, so we need to manage it using  a sort of "caching" with the last_sync_at date.  This it is just a temporal solution and it should be modified once the deltas solution is implemented.
> feat: calculate member usage in workspace

- migrations/20240520034047-remove-sharing-shared-with-constraint.js
- migrations/20240520041258-add-shared-with-type-to-sharings.js
- src/modules/file/file.usecase.ts
- src/modules/sharing/decorators/behalfUser.decorator.ts
- src/modules/sharing/guards/sharing-permissions.decorator.ts
- src/modules/sharing/guards/sharing-permissions.guard.spec.ts
- src/modules/sharing/guards/sharing-permissions.guard.ts
- src/modules/sharing/models/index.ts
- src/modules/sharing/sharing.controller.spec.ts
- src/modules/sharing/sharing.domain.ts
- src/modules/sharing/sharing.module.ts
- src/modules/sharing/sharing.repository.spec.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/dto/get-items-inside-shared-folder.dto.ts
- src/modules/workspaces/dto/share-item-with-member.dto.ts
- src/modules/workspaces/dto/share-item-with-team.dto.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.module.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
- test/fixtures.spec.ts
- test/fixtures.ts
This PR allow users in the workspace to share files and folders with other members in the workspace.
1. **Migration Scripts:**
- Removed `sharings` constraint.
- Added `sharedWithType` column (enum).
2. **Domain Modifications:**
- Updated Sharing domain with `sharedWithType`.
- Added `SharingActionName` to permissions domain.
3. **Repository Changes:**
- Implemented `findPermissions` for sharings.
- Added `canUserPerformActionInSharing` use case.
5. **Guards and Decorators:**
- Created `SharingPermissionsGuard` for checking permissions in shared items.
- Added `BehalfUserDecorator` to retrieve behalfUser from requests.
6. **Controller Updates:**
- Applied `SharingPermissionsGuard` to `createFile` endpoint.
- Added `shareItemWithMember`, `getFoldersInsideSharedFolder`, and …
> [PB-2144] feat: share files and folders with other members in the workspace

- migrations/20240624200747-create-user-tokens-table.js
- src/modules/share/share.module.ts
- src/modules/user/dto/register-notification-token.dto.ts
- src/modules/user/user-notification-tokens.attribute.ts
- src/modules/user/user-notification-tokens.domain.ts
- src/modules/user/user-notification-tokens.model.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.model.ts
- src/modules/user/user.module.ts
- src/modules/user/user.repository.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- test/fixtures.ts
Added `user_notification_tokens` table and an endpoint to register these device tokens. Currently, this is aimed at implementing Apple's push notification service for the macOS client to signal real-time changes. Still, the new table contains a type property in case this could be used for a different purpose in the future.
> [PB-2284]: Feat/register notification token endpoint

- src/modules/workspaces/workspaces.usecase.ts
Workspace was being searched with ownerId for some reason. Removed that part as members can also use that usecase.
> fix: remove search workspace by ownerId on get members

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/workspaces/workspaces.usecase.ts
This PR adds:
1) Required decorator for public sharings (made sure that the sharings are shown correctly on the respective endpoint)
2) Added a missing endpoint for firefox downloads (migrated from drive-server, isn't new logic)
> [PB-2294, PB-2291] feat: enabled share with public users and get folder tree

- src/modules/file/file.controller.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.ts
We were having this error too frequently.  When the new field for workspaces was added, we needed to add the filter for all the parts where we fetch sharings, one was missing.
> [_] fix: fixed error when fetching the sharing type

- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/dto/files-existence-in-folder.dto.spec.ts
- src/modules/folder/dto/files-existence-in-folder.dto.ts
- src/modules/folder/dto/folder-existence-in-folder.dto.spec.ts
- src/modules/folder/dto/folder-existence-in-folder.dto.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.spec.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
The frontend loops through all the files inside a folder to know if there is a file with the same name already created inside it. This operation is a burden for the backend and not eficient.
> [PB-2309] feat: created endpoint for folder and files existence

- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
The frontend uses the `folder/:id` endpoint (created in drive-server) to retrieve all content within a folder. This endpoint is utilized in multiple parts of drive-web, making it challenging to deprecate it all at once. Therefore, we are migrating this endpoint.
**Issue:**
The migrated endpoint currently does not function as expected, returning only 20 files or folders.
**Fix:**
This PR includes changes to ensure the `folder/:folderUuid/content` endpoint works as intended, retrieving all the content within a folder without the 20-item limit.
> [_] fix: endpoint folder/:uuid/content now returns all the content

- migrations/20240719013824-add-item-index-sharings-table.js
- migrations/20240719013827-add-item-id-workspace-item-users-table.js
- src/modules/sharing/sharing.repository.ts
We have a sequential scan made on sharings and workspace_items_users (a table that is expected to grow) making the navigation and queries slow. 
1. Added a required: true to the query to convert left outer joins into inner joins (we do not care about sharings that does not have a workspace_items_users equivalent)
2. Added index on sharings and workspace_items_users. 
For more info, refer to: https://inxt.atlassian.net/browse/PB-2366?focusedCommentId=27484
Requires migrations, please do not merge without running them.
> [PB-2366] fix: workspace_items_users and sharings queries speed improved

- src/modules/sharing/sharing.repository.spec.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
Sharings in workspaces were listing items from other workspaces due to the "OR" query bad formulated. This PR adds a filter by workspaceId to only show sharings in the current workspace
> [_] fix: only show sharings in the current workspace

- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
The previous usage calculation approach was inconsistent. This PR aligns the approach with what we use for individuals.
1. Get usage: Usage is calculated and the value is saved in driveUsage for caching purposes.
2. Upload file: The driveUsage value is used and file.size is added to it. This covers cases such as multiple files upload.
The frontend already calls get usage every time an operation involving drive changes is performed. However, we should not rely solely on this. There are areas for improvement, I'll request a ticket to be opened to address these improvements.
> [PB-2381] fix: workspace usage is now calculated on the fly

- src/modules/folder/folder.repository.ts
We had missing the "sharings"  field while listing folders in a workspace. That field is needed to show the respective icon of "shared" on the UI.
> [_] fix: sharing field is returned while navigating folders

- src/modules/file/file.controller.ts
- src/modules/file/file.module.ts
- src/modules/folder/folder.controller.ts
- src/modules/sharing/decorators/behalfUser.decorator.ts
- src/modules/sharing/guards/sharing-permissions.guard.ts
- src/modules/trash/trash.module.ts
- src/modules/workspaces/guards/workspaces-resources-in-behalf.decorator.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
There were some problems when the workspace header (needed to reuse some endpoints) and the sharings header (navigation through shared folders) are in the same request. This PR addresses them. 
However, I left a TODO comment to find a cleaner way to do this.
> [_] fix: added sharing guard to workspace decorator to enable permissions

- src/modules/sharing/sharing.controller.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/sharing/sharing.service.ts
Allow users to remove sharings in workspaces.
> fix: allow remove sharings in workspaces

- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.ts
Get workspace teams endpoint not is enabled for members and the default team is removed from the response.
> [_] fix: fixed  get workspace teams endpoint permissions and response

- .github/workflows/run-tests.yml
We have a problem with docker compose while running the test action. This command is actually not needed for this action, so I am removing it to make the pipeline work as expected.
> [_] fix: removed build docker compose from unit tests action

- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Endpoint to remove users from workspace. This ultimately uses the same usecase leaveWorkspace so the same logic is applied to user removal (files transfer to owner and team ownership transferred to owner if applicable)
> [PB-2446]: feat/remove workspace member from workspace

- src/modules/workspaces/repositories/team.repository.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
There was a bug where transferred files weren't correctly updated with the creator as the workspace owner. This resulted in a 403 error as the owner ended up attempting to access files that were not theirs.
> [PB-2445]: fix/make-correct-ownership-transfer-when-leaving-the-workspace

- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Temporary check to validate the owner has enough space to receive a removed member's files. This is temorary as it should be replaced by a "transfer ownership"  feature in an upcoming release.
> [PB-2504: fix/file transfer space validation

- src/modules/file/dto/create-file.dto.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
We now encrypt the file names on the backend, this PR ignores the name value sent by the frontend.
> [PB-2770] fix: check file existence with name encrypted backend side

- src/externals/notifications/events/notification.event.ts
- src/externals/notifications/listeners/notification.listener.ts
- src/externals/notifications/notifications.module.ts
- src/externals/notifications/storage.notifications.service.ts
- src/modules/file/file.controller.spec.ts
- src/modules/file/file.controller.ts
- src/modules/file/file.module.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.module.ts
- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.module.ts
Moving websockets implementations to drive-server-wip and also fixing notification on items trashed. 
Original implementation:
https://github.com/internxt/drive-server/blob/46d90c4ac8bff466b190a45d86b548b17a0f3f43/src/config/initializers/notifications.ts
> [PB-2763] fix: add webhooks notifications on storage changes

- src/externals/notifications/listeners/notification.listener.ts
Removing a previous log from the notifications listener. I noticed we reach to almost 3000 records of this log in less than 30 minutes.
This gets logged too much as it is done for multiple actions. We do not need to know every time an event is received, it is enough if we just log the errors and possible not 201 responses from the notifications API.
> [_] chore: removed event handled log

- src/modules/fuzzy-search/look-up.repository.ts
These changes allow the search mechanism to handle a search with multiple words separated by a space correctly. For instance: 
- 'my folder' was not returning the proper results if that exists. Now `to_tsquery` will receive 'my & folder' as the query
> [PB-2973, PB-2974]: fix/replace-spaces-by-the-&-operator-when-searching

- migrations/20241001112638-drop-name-indexes-files.js
- migrations/20241001115355-script-to-remove-plain-name-duplicates-files.js
- migrations/20241001120044-create-index-plainname-folderid-type-exists-unique-files.js
This PR aims to reduce the infra debt related to the files field `name`, which is causing multiple performance problems while not giving advantages of any type. 
The migrations fix the cases where files were being duplicated by name due to not migrating the index where `status = 'EXISTS'` during the transition we did from `deleted`/`removed` fields to `status`.
> [IN-79]: fix/cleanup-files-name-indexes

- migrations/20241004142347-get-folder-ancestor-omit-root-children.js
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
Added a function that exclude direct children of a root folder, in the case of workspaces those are indiviudual root folder. So this fixes an error where currently the ancestors endpoint returns the user's root folder.
> [PB-3045]: fix/get-ancestors-in-workspace

- migrations/20241018040841-modify-get-folder-ancestor-omit-root-children-function.js
- src/modules/auth/decorators/workspace.decorator.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.spec.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
In #407 I excluded both the workspace root folder and the user's root folder from the ancestors result. Turns out that that the ancestors call for personal drives always returns the root folder, so for compatibility this PR fixes this and now only the workspace's root folder is excluded.
> [_]: fix/retrun user's root folder when retrieving ancestors in workspaces

- src/modules/folder/dto/folder-existence-in-folder-old.dto.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
Changing folders/content/:uuid/folders/existence from GET to POST broke the windows client, this PR reintroduces folders/content/:uuid/folders/existence as GET (temporarily?) mantaining the query param that was being used instead of body. 
folders/content/:uuid/folders/existence remained untouched as POST request, as not to break drive-web.
> [_]: fix/restore old folders/existence GET with query param

- src/modules/folder/folder.controller.ts
We should get the input from the body in the case of POST. Marked GET as deprecated so no other platforms use it.
> [_] fix: return body decorator to existence POST

- migrations/20241029132704-update--workspace-owners-space-limit.js
- src/modules/workspaces/domains/workspaces.domain.ts
- src/modules/workspaces/dto/create-workspace-invite.dto.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
All/any unasigned space in the workspace is assigned to the owner. Whenever a user joins space specified in the invite gets deducted from the owner, and whenever a user leaves or is kicked from the workspace that space will be reassigned to the owner.
This PR contains changes made in #402
> [PB-2347]: feat/assign free storage to owner

- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
I was incorrectly calculating the available space in a workspace as `ownerAvailableSpace - spaceAssignedInInvites` this caused a scenario where the last user to accept an invite would be unable to join as the space assigned in their own invitation was being counted as unassignable space. Now when accepting an invite the assignable space is taken as simply the owner's available space
> [PB-3262]: fix/correctly calculate available space in workspace when accepting an invite

- package.json
- yarn.lock
Fixes https://github.com/internxt/drive-server-wip/security/dependabot/67
> chore: upgraded nest platform express due to body-parser vulnerability

- src/externals/notifications/storage.notifications.service.ts
- src/modules/auth/decorators/requester.decorator.spec.ts
- src/modules/auth/decorators/requester.decorator.ts
- src/modules/file/file.controller.spec.ts
- src/modules/file/file.controller.ts
- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/sharing/decorators/behalfUser.decorator.ts
- src/modules/sharing/guards/sharing-permissions.guard.ts
- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.controller.ts
- src/modules/user/user.repository.ts
- src/modules/workspaces/workspaces.controller.spec.ts
- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.module.ts
We need to start sending notifications when a file changes in workspaces. 
The request should be sent to the requester, so we set `request.requester = userMakingTheRequest` in the guard to be able to know exactly who is making the request without relying only on `request.user` which could be the `resourceOwner` (normally not a real user in the case of a workspace file)
> [PB-3447] feat: storage changes notifications support for workspaces

- migrations/20241213035931-fix-update-folder-in-lookup-table-function.js
When you delete a folder, its children folders are not being removed correctly from the lookup table, so searching was showing non accesible folders to the users.
This script just modifies 1 line of the function triggered to fix this behavior. For those who want to compare the changes: original migration [here](https://github.com/internxt/drive-server-wip/blob/b3aec38aa0285d701d926895d357a51fe7eb5d62/migrations/20231004145835-add-triggers-for-lookup.js#L122)
**Old condition:**
` ELSIF OLD.deleted = false AND NEW.removed = false AND (NEW.deleted = true OR NEW.removed = true) THEN
`
**New condition**
`ELSIF (OLD.deleted = false OR OLD.removed = false) AND (NEW.deleted = true OR NEW.removed = true) THEN
`
-----
1. Move the following folder structure to the trash:
- Parent Folder
- Child 1
- …
> [PB-3189] fix: correctly remove children folders from lookup table on delete

- src/modules/auth/auth.controller.spec.ts
- src/modules/auth/auth.controller.ts
This update uses the extended HTTP filter to improve how we log unexpected errors. It cleans up the logs by removing extra spaces and line breaks, making them easier to read and more useful for debugging.
The filter only logs non-HTTP errors, so we avoid cluttering the logs with unnecessary information.
> [_] chore: added extended http filter exception to auth controller 

- src/lib/jwt.ts
- src/modules/auth/jwt.strategy.ts
Previous variable naming was a little confusing, as well as the function. 
This makes the naming a little better and also deletes the function `isTokenIatGreaterThanDate` which just makes everything hard to read.
> [PB-267]: chore/refactor passwordChangedAt middleware variable naming and remove function

- src/modules/auth/auth.controller.ts
- src/modules/user/user.usecase.ts
Previous auth endpoints always convert to lowercase emails. This PR intends to apply the same logic so we do not rely on the client transforming values.
> [_] fix: lower case emails on auth endpoints

- src/modules/user/dto/update-profile.dto.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- https://inxt.atlassian.net/browse/PB-3601
- `PUT /api/users/avatar`
- `DELETE /api/users/avatar `
- `PATCH /api/users/profile`
The error that persisted in the tests of `user.controller.spec.ts` that did not allow this task to finish was due to the order of the imports. For some reason, when adding the code related to loading the user's avatar to the controller, the test file (`user.controller.spec.ts`) stopped working. After doing several investigations and changes, it was discovered that moving the imports could solve the problem (the import of `generateBase64PrivateKeyStub` was moved before the configuration one). I leave this here for future similar errors.
> [PB-3601] feat: migrate user endpoints

- package.json
- src/modules/folder/folder.repository.spec.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/sharing/sharing.service.spec.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.spec.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- yarn.lock
I noticed that toHaveBeenCalledWith was not being asserted as expected, which rendered unit tests relying on it ineffective. This issue has been resolved in recent versions of the @golevelup/ts-jest library, specifically starting from version @golevelup/ts-jest@0.5.1.
Changes:
1. Upgraded the @golevelup/ts-jest library to the latest version.
2. Fixed tests that began failing due to the upgrade and the correct assertion behavior.
3. Removed calls to external functions from user.controllers' Jitsi JWT mock. These calls were unnecessarily slowing down the unit tests (sometimes getting timeout)
> [_] chore: upgraded ts-jest library and fixed unit test

- migrations/20250128040758-increase-keyserver-public-and-private-keys-length.js
Kyber keys are significantly larger compared to ECC keys, necessitating an increase in the size of certain fields to accommodate them.
```
Encrypted kyber keys: 3032 characters
Public kyber key: 1068 characters.
```
> [PB-3625] chore: increase public and private keys size migration

- src/modules/auth/auth.controller.spec.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/decorators/client.decorator.ts
- src/modules/keyserver/key-server.domain.spec.ts
- src/modules/keyserver/key-server.domain.ts
- src/modules/keyserver/key-server.model.ts
- src/modules/keyserver/key-server.repository.ts
- src/modules/keyserver/key-server.usecase.spec.ts
- src/modules/keyserver/key-server.usecase.ts
- src/modules/user/dto/update-password.dto.ts
- src/modules/user/pre-created-user.domain.ts
- src/modules/user/pre-created-users.model.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- test/fixtures.spec.ts
- test/fixtures.ts
- Added missing tests to affected endpoints to ensure backwards compatibility (we just want to check privateKey, publicKey and revocationKey are being returned as expected)
- **GET /public-key/:email**:
- Continues sending `publicKey` field for backward compatibility.
- new keys object containing kyber and ecc keys is returned.
- **Put /password/**:
- Added privateKyberKey as optional body input.
- If users have Kyber keys but a new encrypted Kyber key is not provided, the password update is prevented.
- Removed the private key creation function from the logic. This function was a potential source of issues; in rare cases (e.g., when users without any keys tried to update their password), it could result in empty rows with only privateKeys being created.
- **Post /users/**:
- Keys are …
> [PB-3625] feat: add kyber keys support to update password

- src/modules/auth/auth.controller.spec.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/dto/login-access.dto.ts
- src/modules/keyserver/dto/keys.dto.ts
- src/modules/keyserver/key-server.usecase.spec.ts
- src/modules/keyserver/key-server.usecase.ts
- src/modules/user/dto/create-user.dto.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- **POST /login**:
- Returns `hasKyberKeys` and `hasEccKeys` flags instead of a single `hasKeys` flag.
- Allows differentiation between the presence of Kyber and ECC keys.
- **POST /login/access**:
- Accepts keys via the `keys` object (`KeysDto`) or the legacy fields for ECC encryption (for backwards compatibility)
- If both are provided, the keys inside the `keys` object take priority.
- Returns ECC keys in the legacy structure and includes the `keys` object containing both ECC and Kyber keys.
- **POST /users**:
- Now supports receiving keys via the `keys` object (`KeysDto`).
- Enables submission of both ECC and Kyber keys during user creation.
- **POST /pre-created-users/register**:
- Now supports receiving keys via the `keys` object (`KeysDto`).
- Allows submission of both ECC and …
> [PB-3625] feat: added support for kyber keys on log in and user creation

- migrations/20250128142106-add-view-details-to-permissions.js
This migration was adapted due to an extra column in our prod environment. This just fixes an error we were getting when this migration runs on local environment.
> [_] chore: fixed view details migration for local environments

- src/common/extract-data-from-request.ts
- src/modules/sharing/guards/sharing-permissions.guard.ts
The destructuring of `dataSources` has been modified so that if `metadataOptions` is `undefined`, it is initialized to an empty array. This prevents the error and ensures that the code works correctly even if no data is provided.
The `SharingPermissionsGuard` will call the function `extractDataFromRequest` so it is important to fix this bug.
> [_] fix: invited editor users are now able to share inside shared folders

- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
Endpoint fails when you try to move a trashed children folder from a trashed folder to another folder. The parent folder was being searched using `findById`, but this function searches implicitly for folders with `deleted = true`, so parent folder was not found, causing this unexpected error. 
We need to prevent movements from deleted folders, not from trashed ones.
**Changes**
1. Parent folder is searched using `findOne` without any implicit logic behind.
**How to reproduce it:**
1. Create a parent folder
2. Create a children folder
3. Trash the children folder
4. Trash the parent folder
5. Try to restore the children folder -> internal server error
> [PB-3686] fix: folders with trashed parent can now be moved

- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
When we want to move a folder into another folder that already contains a folder with the same name the folder were trying to move, we rename the current folder and move it. 
When the folder we are moving is trashed and we try to restore it, we do the same thing, we first change the folder's name to move it. However, this was throwing internal server error.
> [PB-3868] fix: trashed folders metadata can now be updated

- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
The VPN API needs to track business plans, but its database does not have information about workspaces or their owners. This makes it difficult to associate users with the correct workspaces.
1. Added workspace owner IDs to the auth token to be able to decode and verify their business plans within the VPN API.
> [_] chore: added workspace owners to auth token

- src/lib/convert-size-to-bytes.spec.ts
- src/lib/convert-size-to-bytes.ts
- src/modules/gateway/dto/check-storage-expansion.dto.ts
- src/modules/gateway/gateway.controller.spec.ts
- src/modules/gateway/gateway.controller.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
This PR implements a new endpoint in the gateway in order to check if the user can stack storage in case the user buys multiple products (e.g. lifetime products). This way, we can be sure that the user does not exceed the set per-user limit - 100TB.
> [_] feat: added check user storage stackability endpoint to gateway

- src/externals/crypto/crypto.service.ts
- src/modules/backups/backup.controller.spec.ts
- src/modules/backups/backup.controller.ts
- src/modules/backups/backup.domain.ts
- src/modules/backups/backup.module.ts
- src/modules/backups/backup.repository.spec.ts
- src/modules/backups/backup.repository.ts
- src/modules/backups/backup.usecase.spec.ts
- src/modules/backups/backup.usecase.ts
- src/modules/backups/device.domain.ts
- src/modules/backups/dto/create-backup.dto.ts
- src/modules/backups/dto/create-device-as-folder.dto.ts
- src/modules/backups/dto/create-device.dto.ts
- src/modules/backups/models/backup.attributes.ts
- src/modules/backups/models/backup.model.ts
- src/modules/backups/models/device.attributes.ts
- src/modules/backups/models/device.model.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.module.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- There are over 500 lines of code in tests(*.spec.ts)
- There are new files that don't require testing
---
- Migrate `limit` and `backup deviceAsFolder` endpoints
---
- `GET` _/api/limit_ `server -> wip` _/api/users/limit_
- `POST` _/api/backup/activate `server_ -> wip` _/api/backup/activate_
- `POST` _/api/backup/deviceAsFolder_ `server -> wip` _/api/backup/deviceAsFolder_
```
Body { "deviceName": string }
```
- `GET` _/api/backup/deviceAsFolder_ `server -> wip` _/api/backup/deviceAsFolder_
- `GET` _/api/backup/deviceAsFolder/:id_ `server -> wip` _/api/backup/deviceAsFolder/:uuid_
Param: `:uuid` == Folder.uuid`
- `PATCH` _/api/backup/deviceAsFolder/:id_ `server -> wip` _/api/backup/deviceAsFolder/:uuid_
Param: `:uuid` == Folder.uuid`
```
Body { "deviceName": string }
```
> [PB-4104] feat: Migrate limit and backup device endpoints

- src/modules/file/file.controller.spec.ts
- src/modules/file/file.controller.ts
- src/modules/thumbnail/dto/create-thumbnail.dto.ts
- src/modules/thumbnail/dto/thumbnail.dto.ts
- src/modules/thumbnail/thumbnail.model.ts
- src/modules/thumbnail/thumbnail.module.ts
- src/modules/thumbnail/thumbnail.repository.spec.ts
- src/modules/thumbnail/thumbnail.repository.ts
- src/modules/thumbnail/thumbnail.usecase.spec.ts
- src/modules/thumbnail/thumbnail.usecase.ts
- Migrating storage thumbnail endpoint
---
- `drive-server` `POST` _/storage/thumbnail_ `->` `wip` _/files/thumbnail_
```
Body
{
"fileId": 9999,
"maxWidth": 300,
"maxHeight": 300,
"type": "png",
"size": 19658,
"bucketId": "BUCKET9a85f433f5079cd72e",
"bucketFile": "BUCKET2c52b2da002bf29f8a",
"encryptVersion": VERSION
}
```
> [PB-4108] Feat: migrate thumbnail endpoint

- src/modules/backups/backup.controller.spec.ts
- src/modules/backups/backup.controller.ts
- src/modules/backups/backup.repository.spec.ts
- src/modules/backups/backup.repository.ts
- src/modules/backups/backup.usecase.spec.ts
- src/modules/backups/backup.usecase.ts
- Migrate some backup and device endpoints
---
- `GET` _/api/backup/device_  `server -> wip` _/api/backup/devices_
- `DELETE` _/api/backup/device/:deviceId_  `server -> wip` _/api/backup/devices/:deviceId_
Param: `:deviceId == Device.id`
- `GET` _/api/backup/:mac_ `server -> wip` _/api/backup/:mac_
Param: `:mac == Device.mac`
- `DELETE` _/api/backup/:backupId_ `server -> wip` _/api/backup/:backupId_
Param: `:backupId` == Backup.id`
> [PB-4106] Feat: migrate backup and device endpoints

- src/app.module.ts
- src/common/http-global-exception-filter.exception.spec.ts
- src/common/http-global-exception-filter.exception.ts
- src/modules/auth/auth.controller.ts
- src/modules/auth/decorators/client.decorator.ts
- src/modules/file/file.controller.ts
- src/modules/folder/folder.controller.ts
- src/modules/gateway/gateway.controller.ts
- src/modules/user/user.controller.ts
- src/modules/workspaces/workspaces.controller.ts
This PR improves our logging format to ensure proper display in our logs ingest tool by replacing the default multiline NestJS Global Exception Filter with a custom implementation that formats logs as single-line JSON objects, categorizes errors by type (external service errors via Axios, database errors from Sequelize, and unexpected application errors).
- Add unique error ID generation using UUID for any non intrinsic error
- Categorize errors by type (Database, External Service, or Unexpected)
To remove colors from the logs, we're using NestJS v10, so we should set the `NO_COLOR` environment variable to some non-empty string.
> [PB-4129] feat(logger): added global exception filter

- src/common/http-global-exception-filter.exception.spec.ts
- src/common/http-global-exception-filter.exception.ts
1. Use subcategories instead of just DATABASE, EXTERNAL_ERROR so we can search all errors by just using EXTERNAL_ERROR.
> [PB-4129] feat(logger): use subcategories inside UNEXPECTED_ERRROR

- src/modules/workspaces/workspaces.controller.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Fixed an error when sending `WORKSPACE_LEFT` notifications when removing a member from the workspace. As the workspaceMember data retrieved from db was not including the user's data, causing an error when trying to access user.email when sending the notification
> [_]: fix/include member data when sending user removed notifications

- src/modules/file/file.controller.spec.ts
- src/modules/file/file.controller.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
Attempt to delete files by `fileId`. If file is found in the db a normal delete flow would be attempted, if it is not found we attempt to directly delete if from network.
Would be the equivalent of `DELETE: <drive-server>/storage/bucket/:bucket/file/:fileId`
> [_]: chore/implement deleteFileByFileId functionality

- package.json
- yarn.lock
I noticed on my local that our current jsonWebToken Version is not compatible with 9.0.9 types, this breaks our tests. For some reason tests in the original PR were executed successfully.
This is just a rollback to a compatible version.
> fix(deps): rollback type/jsonwebtoken version to 9.0.2

- src/main.ts
Colored logs add noise to our logs platform. This PR just removes logs colors so we can have cleaner logs.
1. Remove logs colors if environment is not development.
> [_] chore(logs): disable logs colors if not on dev

- src/common/http-global-exception-filter.exception.spec.ts
- src/externals/notifications/storage.notifications.service.spec.ts
- src/modules/app-sumo/app-sumo.usecase.ts
- src/modules/auth/auth.controller.spec.ts
- src/modules/gateway/gateway.controller.spec.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/keyserver/key-server.usecase.spec.ts
- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.usecase.spec.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
This just mocks the logger so we do not have a lot of logs when running `yarn test`. Also, I removed the use of Response object to return an error response so we can use the NestJS built-in http errors.
> [_] refactor: userController error handling and unit tests logger

- src/modules/sharing/sharing.domain.ts
- src/modules/sharing/sharing.repository.ts
- src/modules/user/pre-created-user.domain.ts
- src/modules/user/pre-created-users.attributes.ts
- src/modules/user/pre-created-users.model.ts
- src/modules/user/user.module.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- test/fixtures.ts
This is just a part of the code already approved here: https://github.com/internxt/drive-server-wip/pull/465. 
I am splitting that PR into multiple PRs so we can support this feature incrementally without breaking any platform. 
No hybrid encryption is going to be taken into account for pre created users yet, this just prepares the function to support it.
**Workspaces are not affected by this.**
Changes
1. Decrypt private key using hybrid decryption functions
2. Support for hybrid encryption when replacing pre created users sharings invitations
> feat(PQ): added PQ encryption to replace pre created user function

- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/workspaces/repositories/workspaces.repository.spec.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
This is just a PR that adds some of the functions we will need for recovering/resetting users' accounts. This just takes functions from https://github.com/internxt/drive-server-wip/pull/506 to split the PR into small pieces.
1. Added empty workspace function. 
2. Added remove user from all invited workspaces.
> feat(recover-account): add reset workspace functions

- src/externals/asymmetric-encryption/asymmetric-encryption.service.spec.ts
- src/lib/path.spec.ts
- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/user/user.usecase.spec.ts
- Files without an extension are now found regardless of their empty-null value
Another PR will be needed to address this duality (empty vs. null) by setting only one as the default and preventing the other from occurring
> [PB-4092]: fix/find-files-with-empty-type

- src/lib/import-esm-package.ts
We were getting  the `Test environment has been torn down` error randomly when running our unit tests on github actions. I was able to reproduce this on my local by setting `--verbose --detectOpenHandles --debug` flags in the test command in package.json. 
Note: 
We need to import ESM modules using this function due to NestJS limitations.
1. Modified importEsmPackage function to prevent race conditions.
> [_] fix(tests): fixed tests failing randomly due to kyber provider

- src/modules/folder/folder.module.ts
- src/modules/user/user.module.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/workspaces.usecase.ts
1. User is removed from non owned workspaces when they reset their password. All owned files are transferred to the owner.
2. Sharings are removed when users reset their account
> [PB-3702] feat(reset-account): empty workspace and sharings when user resets their account

- src/modules/user/user.usecase.ts
This is part of already closed and approved https://github.com/internxt/drive-server-wip/pull/465. I am just adding parts of it to prevent production from breaking as mentioned here https://github.com/internxt/drive-server-wip/pull/497
We do not return the kyber keys yet to prevent the frontend from using hybrid encryption due to some conflict with the encrypted value length. It seems that sometimes the encrypted mnemonic has a length longer than the limit of the field in the database.
> feat(pre-created-users): generate hidden kyber keys

- src/modules/user/user.controller.ts
This passes the frontend generated new public kyber key to the replace precreated user function so any pre created user that has hybrid invitations and already existent private and public kyber keys can process those invitations.
Note: this flow is not going to be possible unless we start returning the public kyber key when precreated users are generated, so all the guest sharings are still being handled using ECC encryption for the moment.
> feat(pre-created-users): pass new generated kyber key replacePreCreatedUser

- src/modules/backups/backup.usecase.spec.ts
- src/modules/backups/backup.usecase.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
This PR forces updated_at when the endpoint Patch /backup/deviceAsFolder is reached. This aligns with the drive-server's behavior, the mac team was having problems because of this. 
However, I do not feel it is the best approach to force the `updated_at` despite the name of the backup being the same, I would suggest another endpoint for this in the future. It seems this endpoint is misused by the apps.
> fix(backups): update_at is updated 

- migrations/20250425153614-increase-encryption-key-size.js
- migrations/20250425153626-increase-sharing-invitation-encryption-key-size.js
This addresses the problem with some encryption keys being bigger than 2000 characters (approx 2080 characters).
Related:
https://github.com/internxt/drive-server-wip/pull/497
> fix(pre-created-users): increase encryption key size

- src/modules/folder/folder.controller.spec.ts
- src/modules/folder/folder.controller.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/folder/folder.usecase.ts
There was a folderUsecases function that was modified a few months ago. It was used in multiple places, so by adding the logic to prevent rootFolders deletion, it broke the workspaces deletion flow.
Changes
1. Added another function that prevents the root folder deletion so it can be used from any controller if needed.
2. Changes made to deleteByUser were rolled back.
> [_] fix(folders-deletion): workspaces root folders are now deleted correctly.

- migrations/20250508230425-populate-folder-uuid-files-table.js
As autoincremental IDs have a limit and as files are being related to folders by using the `folder_id` field, an autoincremental ID, we started using a `folder_uuid` field to avoid hitting the limit in the near future. The issue was that running an update on hundreds of millions of files was infeasible, hence, we did not set the field to NOT NULL, but that should be the ideal situation. The idea is to do this refilling incrementally.
A migration is run. This migration contains a script that populates the records incrementally. A retry system is implemented in case of small downtimes. Also, the migration is idempotent; running it multiple times does not cause duplicate records.
The performance of the SELECT-based query to find, for each file, its parent folder UUID, is the following: …
> [PB-4371] feat(files): populate file records with missing folder_uuid

- src/modules/backups/backup.repository.spec.ts
- src/modules/backups/backup.repository.ts
- src/modules/backups/backup.usecase.spec.ts
- src/modules/backups/backup.usecase.ts
- src/modules/user/dto/responses/get-user-usage.dto.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
Added backups usage and total usage to the usage endpoint response to allign with what is currently expected by each platform
> [PB-4369]: fix/include backup usage in usage response

- src/main.ts
- src/modules/folder/folder.controller.ts
Just taking care of some controllers that were not throwing errors back despite receiving errors from the service.
1. Removed try / catch from two endpoints.
2. Removed call to logger(....) as we can log from the global filter.
> [_] chore/remove-custom-in-controllers-and-set-compact-to-logger

- src/modules/cache-manager/cache-manager.service.ts
- src/modules/user/user.usecase.ts
add limit cahce hit and misses
> chore: enhance cache logging with debug information

- src/externals/crypto/crypto.service.ts
- src/lib/jwt.ts
- src/modules/user/dto/legacy-recover-account.dto.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- src/modules/workspaces/repositories/workspaces.repository.ts
- Added `legacy-recover-account` endpoint.
- WorkspaceUsers encrypted key of owned workspaces are updated with ecc encrypted mnemonic when account is recovered.
- User is removed from invited sharings and workspaces due to new keys generated. **We should warn users about this.**
- New generated keys are also saved
> feat(recover-account): recover account with legacy backup file 

- src/modules/cache-manager/cache-manager.service.spec.ts
- src/modules/cache-manager/cache-manager.service.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/user/user.usecase.ts
Optimistically update the user limit in the cache when the gateway is triggered on a plan change. Instead of deleting the cache entry, we optimistically set the new value with a low TTL of one minute. This approach helps to avoid potential race conditions during orchestration.
> [_]: fix/optimistic cache updates

- src/modules/sharing/sharing.controller.ts
This handles two code smells that were reducing our realibility ranking.
> [_] refactor(sharings-errors): leave logging to global exception filter

- src/modules/file/file.model.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/thumbnail/dto/thumbnail.dto.ts
- src/modules/thumbnail/thumbnail.attributes.ts
- src/modules/thumbnail/thumbnail.domain.ts
- src/modules/thumbnail/thumbnail.model.ts
- src/modules/thumbnail/thumbnail.repository.spec.ts
- src/modules/thumbnail/thumbnail.repository.ts
- src/modules/thumbnail/thumbnail.usecase.spec.ts
- src/modules/thumbnail/thumbnail.usecase.ts
After introducing fileUuid field to the thumbnails model in #584 this PR updates the thumbnail relationships in the codebase to utilize UUIDs instead of incremental IDs.
- Refactored SequelizeThumbnailRepository to replace findByFileId with findByFileUuid, allowing retrieval of thumbnails based on UUIDs.
- Updated ThumbnailUseCases to utilize the new UUID-based methods, including changes to createThumbnail and deleteThumbnailByFileUuid.
> [PB-4416]:  chore/file UUID in thumbnails

- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/user/dto/responses/get-upload-status.dto.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
Created the `GET /users/me/upload-status ` to determine wether the user has uploaded any files. This takes into account files of any status so deleted files should be included. 
This is helpful in determining to show the onboarding tutorial on the web app.
> [_]: feat(users)/implement get me/upload-status endpoint to determine wether a user has ever uploaded any files

- .github/workflows/stale-and-close.yml
This PR adds a github action that will mark as stalled any inactive PR.
- Inactive PRs are marked as stalled if they have been inactive for more than 15 days.
- Any PR stalled for more than 30 days, will be closed. Branches won't be closed so contributors can reopen any PR again if needed.
> chore(actions): added close stalled PRs action

- src/modules/sharing/sharing.controller.spec.ts
- src/modules/sharing/sharing.controller.ts
Introduce `GET /sharings/public/domains `which returns a list of domains specified in the env config.
This endpoint is meant as a replacement of `GET storage/share/domains`
> [_]: feat/move get share domains endpoint

- .eslintrc.js
Adding some new eslint rules to help prevent common issues marked by sonar.
`prefer-readonly`: variables not declared as readonly was possibly the biggest number of issues present in the codebase.
`prefer-optional-chain`: instead of doing `payload && payload.uuid` we should opt for `payload?.uuid`
`consistent-type-imports`: would help prevent cyclic imports. most of the cyclic imports I found while reviewing sonar issues could be fixed by simply opting to import types
> [_]: chore(eslint): update rules to improve code quality

- src/externals/bridge/bridge.service.spec.ts
- src/modules/feature-limit/feature-limits.guard.spec.ts
- src/modules/file/file.controller.spec.ts
- src/modules/folder/folder.usecase.spec.ts
- src/modules/sharing/sharing.controller.ts
- src/modules/workspaces/guards/workspaces.guard.spec.ts
This PR removes the use of some deprecated function in our test suites and removes unused arguments in sharingController. It does not intend to increase the test coverage we have currently.
> [_] refactor: stop using some deprecated functions and solved code smells

- src/externals/http/http.module.ts
I set the timeout to 16 seconds due to a problem with the TLS handshake taking too much time between drive-server and notifications. The problem was identified and addressed, so we are going back to the default values.
> [_] chore: reduce axios timeout to default value

- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Delete workspace and its contents and initialize a new one upon resetting the user's account
> [_]: feat/completely clear workspace on reset

- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/trash/dto/controllers/delete-item.dto.ts
- src/modules/trash/dto/controllers/move-items-to-trash.dto.ts
- src/modules/trash/trash.controller.spec.ts
- src/modules/trash/trash.controller.ts
- src/modules/trash/trash.usecase.spec.ts
Continuing with the codebase migration to get rid of logic that still relies on numeric fileIds this pr introduces:
- Delete old unreferenced code that relied on numeric ileId usages
- deleteFilesByUser in file.repository now performs a where based on uuid instead of the numeric id
- Refactor in delete /trash/ to first search based on file uuid, although the fileId search logic might be safely delleted?
- Updated test logic to reflect any changes
> [PB-4416]: refactor/replace-fileid-usage-with-uuid-in-trash-and-file-modules

- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
Update `verifyAndDecodeAccountRecoveryToken` to use getEnv() instead of configService.get to try and fix the 403 forbidden error that only happens in this endpoint
> [_]: fix/update JWT secret retrieval and add debug logging

- migrations/20250730231958-create-updated-at-folders-index.js
This index is required for the deleted items cleanup cronjob. 
We will be looking for removed folders updated between a specific range of time instead of scanning the entire database looking for any undeleted folder.
Related: https://github.com/internxt/drive-server-wip/pull/638
>  [PB-4693] feat: add updated at index for removed folders

- src/modules/jobs/tasks/deleted-items-cleanup.task.spec.ts
- src/modules/jobs/tasks/deleted-items-cleanup.task.ts
This PR intends to add more logs to the deleted items cleanup job. We want to be able to check how the job is behaving before closing this task.
> [_] feat: added more logs to deleted items cleanup job

- src/modules/file/file.repository.spec.ts
- src/modules/file/file.repository.ts
- src/modules/file/file.usecase.ts
- src/modules/folder/folder.repository.spec.ts
- src/modules/folder/folder.repository.ts
- src/modules/folder/folder.usecase.ts
- src/modules/trash/trash.usecase.spec.ts
- src/modules/trash/trash.usecase.ts
A refactor of @larry-internxt's https://github.com/internxt/drive-server-wip/pull/615. 
It was easier to create another branch instead of working from the original PR. 
This PR uses a raw query to delete folders and files in batches instead of making SELECT and UPDATE queries sequentially. We tend to encourage the use of Sequelize ORM for all of our queries; however, this endpoint's performance could be significantly benefited by using a raw query that combines updating and selecting.
> [_] fix: empty trash timeout fixed when there are too many items

- src/modules/file/file.usecase.spec.ts
- src/modules/file/file.usecase.ts
- src/modules/usage/usage.repository.ts
- src/modules/usage/usage.service.spec.ts
- src/modules/usage/usage.service.ts
We do not really need findOrCreate now that we added a constraint. It also did not prevent any error due to the TOCTOU / race condition it creates internally (a select + insert query).
> [_] Fix/usage creation

- migrations/20250825221935-create-user_id-period-type-partial-constraint.js
This adds an unique constraint using INDEX as postgresql does not allow partial constraints by default. When two calls to `/usage` are made at the same time, a race condition is created, therefore, two records are created in the table with the same value.
⚠️ We need to clean the usages table before running the index creation !!
> [_] fix(usage): add unique constraint to usage table

- src/main.ts
- Removes unnecessary '/api' from swagger endpoints (swagger url remains the same)
> [_]: fix/remove-api-from-swagger-endpoints

- src/modules/cache-manager/cache-manager.service.spec.ts
- src/modules/cache-manager/cache-manager.service.ts
- src/modules/user/user.controller.spec.ts
- src/modules/user/user.controller.ts
- src/modules/user/user.usecase.spec.ts
- src/modules/user/user.usecase.ts
- Added methods to CacheManagerService for getting, setting, and deleting user avatars.
- Updated UserController to use cached avatar retrieval.
- Refactored user use cases to include getCachedAvatar logic, handling cache hits and misses.
- Enhanced unit tests to cover new avatar caching functionality and edge cases.
> [PB-4731]: implement caching for user avatars in cache manager

- migrations/20250916110659-create-files-user-updated-statistics.js
Queries using `(user_id, updated_at)` conditions were using inefficient single column indexes instead of the composite index, causing slow performance on delta calculations.
Add extended statistics to capture correlation between `user_id` and `updated_at` columns, enabling the query planner to make better index selection decisions.
Extended statistics accuracy depends on the underlying single-column statistics quality. For a table with 668M rows:
- **Default (100):** Captures 100 most common values and ~100 histogram buckets
- **Increased (500):** Captures 500 most common values and ~500 histogram buckets
- **Result:** More granular data distribution understanding, leading to better correlation detection between `user_id` and `updated_at`
The table is really big, so we actually can …
> [PB-2394] chore: create extended statistics for user_id, updated_at

- migrations/20250916144443-add-name-column-to-limits-table.js
- migrations/20250916145418-seed-new-pricing-tiers.js
Add WebDAV Access Limits for Pricing Tiers. These tiers are managed by drive-server, payments needs to map every tier to its respective equivalent in payments.
- Added name column to limits table for better limit differentiation. Some limits might look the same as they share the same label (required for querying), so `name` can help us to differentiate between limits.
- Created new pricing tiers (Free, Essential, Premium, Ultimate, Standard Business, Pro Business)
- Used hardcoded v4 uuids so we have the same uuids across all environments, we do not want to complicate our development flow.
> [PB-4942] feat(tiers): add new tiers seed

- migrations/20250925185947-reassign-free-tier-label.js
We currently have a duplicate free tier in production. Users are being assigned to the original free tier (10gb_individual label) by default, but there's also a duplicate tier with UUID `3a8f239e-9c4d-494a-9255-de65ab909483` that was incorrectly created some days ago.
This PR removes the duplicated tier and assign the correct label to the 10gb_individual tier. We already assign that tier to the free users on account creation, so it does not make sense to have a duplicate.
1. Removing the duplicate tier: Deletes the incorrectly created free tier (3a8f239e-9c4d-494a-9255-de65ab909483)
2. Reassigning tier relationships: Moves any tier-limit relationships from the duplicate to the original tier
3. Updating the original tier: Changes the existing 10gb_individual tier to use the correct …
> [_] fix/remove-duplicate-free-tier-from-database

- src/common/audit-logs/audit-log.service.spec.ts
- src/common/audit-logs/audit-log.service.ts
- src/common/audit-logs/audit-logs.module.ts
- src/common/audit-logs/decorators/audit-log.decorator.ts
- src/common/audit-logs/interceptors/audit-log.interceptor.spec.ts
- src/common/audit-logs/interceptors/audit-log.interceptor.ts
- src/common/audit-logs/utils/path-extractor.util.ts
Dependency: https://github.com/internxt/drive-server-wip/pull/728
This PR adds a decorator that would let us to audit any endpoint by just setting it up correctly.
We'll decorate the controllers in another PR.
> [PB-4689] feat/audit logs decorator and service

- src/modules/gateway/dto/initialize-workspace.dto.ts
- src/modules/gateway/gateway.usecase.spec.ts
- src/modules/gateway/gateway.usecase.ts
- src/modules/workspaces/workspaces.usecase.spec.ts
- src/modules/workspaces/workspaces.usecase.ts
Adds optional tierId parameter to workspace initialization to set the tier during workspace creation.
- Added tierId field to InitializeWorkspaceDto with UUID validation
- Updated GatewayUseCases.initializeWorkspace() to validate tier exists before creation
- Modified WorkspacesUsecases.initiateWorkspace() to set tier on workspace user during initialization
> feat(gateway): set tier on workspace creation
